# Generated by Django 2.1 on 2018-07-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TumengClans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clanname', models.CharField(max_length=50)),
                ('clantag', models.CharField(max_length=30)),
                ('ctime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
