# Generated by Django 2.1 on 2018-07-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='pushOrchangeTag',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='uptime',
        ),
    ]
